# Generated by Django 5.1.3 on 2024-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='time_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('normal', 'Normal Widget'), ('time', 'Time Widget')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='widget',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
