# Generated by Django 5.1.3 on 2024-11-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_widget_time_zone_widget_widget_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='time_zone',
        ),
    ]
