# Generated by Django 5.1.3 on 2024-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_remove_widget_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('normal', 'Normal Widget'), ('time', 'Time Widget'), ('weather', 'Weather Widget')], default='normal', max_length=10),
        ),
    ]
