# Generated by Django 5.1.3 on 2024-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_widget_city_alter_widget_widget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='city',
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('normal', 'Normal Widget'), ('time', 'Time Widget')], default='normal', max_length=10),
        ),
    ]
