# Generated by Django 5.1.3 on 2024-11-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_widget_city_alter_widget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
