name: Bug Report
description: Report a bug
title: Bug Report
projects: "TheMirror/TheMirror"
labels: "bug"
body:
  - type: textarea
    attributes:
      label: The problem
      description: What problem are you experiencing?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the problem.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
