name: Feature request
description: Request a feature
title: Feature request
projects: "MirrorBoys/3"
labels: "Enhancement"
body:
  - type: textarea
    attributes:
      label: The feature
      description: Describe the feature you would like to have.
    validations:
      required: true
  - type: dropdown
    label: Priority
    options:
      - Must
      - Should
      - Could
