name: Feature request
description: Request a feature
title: Feature request
projects: "MirrorBoys/3"
labels: "enhancement"
body:
  - type: textarea
    attributes:
      label: The feature
      description: Describe the feature you would like to have.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: What priority should this feature have?
      multiple: false
      options:
        - Must have
        - Should have
        - Could have
      default: 2
    validations:
      required: true
