name: Feature request
description: Request a feature
title: Feature request
projects: "MirrorBoys/3"
type: "feature"
body:
  - type: textarea
    attributes:
      label: The feature
      description: Describe the feature you would like to have.
    validations:
      required: true
