name: Label Issue by Priority

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Determine label based on priority
        id: label_priority
        run: |
          if [[ "${{ github.event.issue.body }}" == *"Must have"* ]]; then
            echo "label=requirement-must" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.body }}" == *"Should have"* ]]; then
            echo "label=requirement-should" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.body }}" == *"Could have"* ]]; then
            echo "label=requirement-could" >> $GITHUB_ENV
          else
            echo "No matching priority found."
            exit 0
          fi

      - name: Add label to issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.label }}
