name: Label Issue by Priority

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Determine label based on priority
        id: label_priority
        run: |
          if [[ "${{ github.event.issue.body }}" == *"Must have"* ]]; then
            echo "label=requirement-must" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.body }}" == *"Should have"* ]]; then
            echo "label=requirement-should" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.body }}" == *"Could have"* ]]; then
            echo "label=requirement-could" >> $GITHUB_ENV
          else
            echo "No matching priority found."
            exit 0

      - name: Get current labels
        id: get_labels
        uses: actions-ecosystem/action-get-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove existing priority labels if present
        uses: actions-ecosystem/action-remove-labels@v1
        if: contains(steps.get_labels.outputs.labels, 'requirement-must') || 
            contains(steps.get_labels.outputs.labels, 'requirement-should') || 
            contains(steps.get_labels.outputs.labels, 'requirement-could')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ${{ contains(steps.get_labels.outputs.labels, 'requirement-must') && 'requirement-must' || '' }}
            ${{ contains(steps.get_labels.outputs.labels, 'requirement-should') && 'requirement-should' || '' }}
            ${{ contains(steps.get_labels.outputs.labels, 'requirement-could') && 'requirement-could' || '' }}

      - name: Add new label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.label }}
